//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhereToFly.App.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WhereToFly.App.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CZML Layer.
        /// </summary>
        internal static string LayerType_CzmlLayer {
            get {
                return ResourceManager.GetString("LayerType_CzmlLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Layer.
        /// </summary>
        internal static string LayerType_LocationLayer {
            get {
                return ResourceManager.GetString("LayerType_LocationLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cesium OpenStreetMap Buildings Layer.
        /// </summary>
        internal static string LayerType_OsmBuildingsLayer {
            get {
                return ResourceManager.GetString("LayerType_OsmBuildingsLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track Layer.
        /// </summary>
        internal static string LayerType_TrackLayer {
            get {
                return ResourceManager.GetString("LayerType_TrackLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpine hut.
        /// </summary>
        internal static string LocationType_AlpineHut {
            get {
                return ResourceManager.GetString("LocationType_AlpineHut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bridge.
        /// </summary>
        internal static string LocationType_Bridge {
            get {
                return ResourceManager.GetString("LocationType_Bridge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable car.
        /// </summary>
        internal static string LocationType_CableCar {
            get {
                return ResourceManager.GetString("LocationType_CableCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle.
        /// </summary>
        internal static string LocationType_Castle {
            get {
                return ResourceManager.GetString("LocationType_Castle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cave.
        /// </summary>
        internal static string LocationType_Cave {
            get {
                return ResourceManager.GetString("LocationType_Cave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Church.
        /// </summary>
        internal static string LocationType_Church {
            get {
                return ResourceManager.GetString("LocationType_Church", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying landing place.
        /// </summary>
        internal static string LocationType_FlyingLandingPlace {
            get {
                return ResourceManager.GetString("LocationType_FlyingLandingPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying takeoff.
        /// </summary>
        internal static string LocationType_FlyingTakeoff {
            get {
                return ResourceManager.GetString("LocationType_FlyingTakeoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flying winch towing.
        /// </summary>
        internal static string LocationType_FlyingWinchTowing {
            get {
                return ResourceManager.GetString("LocationType_FlyingWinchTowing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string LocationType_Information {
            get {
                return ResourceManager.GetString("LocationType_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lake.
        /// </summary>
        internal static string LocationType_Lake {
            get {
                return ResourceManager.GetString("LocationType_Lake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live waypoint.
        /// </summary>
        internal static string LocationType_LiveWaypoint {
            get {
                return ResourceManager.GetString("LocationType_LiveWaypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meteo station.
        /// </summary>
        internal static string LocationType_MeteoStation {
            get {
                return ResourceManager.GetString("LocationType_MeteoStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        internal static string LocationType_Parking {
            get {
                return ResourceManager.GetString("LocationType_Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        internal static string LocationType_Pass {
            get {
                return ResourceManager.GetString("LocationType_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public transport: Bus.
        /// </summary>
        internal static string LocationType_PublicTransportBus {
            get {
                return ResourceManager.GetString("LocationType_PublicTransportBus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public transport: Train.
        /// </summary>
        internal static string LocationType_PublicTransportTrain {
            get {
                return ResourceManager.GetString("LocationType_PublicTransportTrain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restaurant.
        /// </summary>
        internal static string LocationType_Restaurant {
            get {
                return ResourceManager.GetString("LocationType_Restaurant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summit.
        /// </summary>
        internal static string LocationType_Summit {
            get {
                return ResourceManager.GetString("LocationType_Summit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swimming spot.
        /// </summary>
        internal static string LocationType_SwimmingSpot {
            get {
                return ResourceManager.GetString("LocationType_SwimmingSpot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thermal.
        /// </summary>
        internal static string LocationType_Thermal {
            get {
                return ResourceManager.GetString("LocationType_Thermal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnpoint.
        /// </summary>
        internal static string LocationType_Turnpoint {
            get {
                return ResourceManager.GetString("LocationType_Turnpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string LocationType_Undefined {
            get {
                return ResourceManager.GetString("LocationType_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via ferrata.
        /// </summary>
        internal static string LocationType_ViaFerrata {
            get {
                return ResourceManager.GetString("LocationType_ViaFerrata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewpoint.
        /// </summary>
        internal static string LocationType_Viewpoint {
            get {
                return ResourceManager.GetString("LocationType_Viewpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waypoint.
        /// </summary>
        internal static string LocationType_Waypoint {
            get {
                return ResourceManager.GetString("LocationType_Waypoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webcam.
        /// </summary>
        internal static string LocationType_Webcam {
            get {
                return ResourceManager.GetString("LocationType_Webcam", resourceCulture);
            }
        }
    }
}
