# Build for the AOT test project

name: Build AOT test project

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Publish AOT test project .NET
      run: >
        dotnet publish
        src/App/AotTest/WhereToFly.App.AotTest.csproj
        -c Release
        -f net9.0

    - name: Publish AOT test project .NET Android
      if: always()
      run: >
        dotnet publish
        src/App/AotTest/WhereToFly.App.AotTest.csproj
        -c Release
        -f net9.0-android
        -r android-arm64

    - name: Publish AOT test project .NET Windows
      if: always()
      run: >
        dotnet publish
        src/App/AotTest/WhereToFly.App.AotTest.csproj
        -c Release
        -f net9.0-windows10.0.19041.0
