# Build and Deployment for the Where-to-fly WebAPI

name: Build + Deploy WebAPI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Publish
      run: dotnet publish src/WebApi/Core/WhereToFly.WebApi.Core.csproj --output "published"

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v3
      with:
        app-name: WhereToFlyWebApi
        publish-profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_PROFILE }}
        package: "published"

    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: WebAPI
        path: "published"
