# Build for the Where-to-fly Windows app

name: Build Windows app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Publish Windows app
      run: >
        dotnet publish
        src/App/Maui/WhereToFly.App.Maui.csproj
        -f net9.0-windows10.0.19041.0
        --self-contained true
        /p:PublishSingleFile=true
        /p:PublishTrimmed=true
