# Build for the Where-to-fly Android app

name: Build Android app

on:
  pull_request:
    branches: [ "app-build-github-action" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3

    - name: Build WebLib npm package
      run: |
        cd src/Shared/WebLib
        npm install
        npm run build-release

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.1.3

    - name: Build Android .apk
      run: msbuild src/App/Android/WhereToFly.App.Android.csproj /restore /t:SignAndroidPackage /p:Configuration=Release

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: APK file
        path: src/App/Android/bin/Release/de.vividos.app.wheretofly.android-Signed.apk
