# Build for the Where-to-fly Android app

name: Build Android app

on:
  pull_request:
    branches: [ "app-build-github-action" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Install Xamarin.Android
      shell: pwsh
      run: |
        dotnet tool install --global boots
        boots --stable Xamarin.Android

    - name: Build .apk
      run: msbuild src/App/Android/WhereToFly.App.Android.csproj /restore /t:SignAndroidPackage /p:Configuration=Release
