# Build for the Where-to-fly Android MAUI app

name: Build Android MAUI app

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Build Android MAUI .apk
      run: >
        dotnet publish src/App/Maui/WhereToFly.App.Maui.csproj -f net8.0-android34.0

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: APK file
        path: src/App/Maui/bin/Release/net8.0-android34.0/publish/de.vividos.app.wheretofly.android-Signed.apk
